Issue11
lmazuel/onagui pull request #29
Opened 2017-03-30 15:42 UTC by tfrancart

Comme son nom ne l'indique pas cette branche traite le ticket 11 (pouvoir aligner seulement les concepts modifiés après une certaine date)

2017-04-02 18:41 UTC, lmazuel requested changes

2017-04-02 18:41 UTC, lmazuel commented on src/main/java/fr/onagui/alignment/container/OWLAPIContainer.java
> +		return null;
throw new UnsupportedOperationException("Not supported in OWL for now");

2017-04-02 18:41 UTC, lmazuel commented on src/main/java/fr/onagui/alignment/method/NewAlignment.java
> +public class NewAlignment<ONTORES1, ONTORES2> extends LabelAlignmentMethod<ONTORES1, ONTORES2> {
Faudrait peut-etre lui donner un plus joli nom avant le merge?
Si c'est une variante de ISub avec Date, le nommer DatedISub ou au moins quelque chose de clair. "New alignement" ne donne pas d'info sur ce que c'est.

2017-04-02 18:41 UTC, lmazuel commented on src/main/java/fr/onagui/control/AlignmentControler.java
> +			DefaultMutableTreeNode rootFrom2, Date date1, Date date2) {
Detail: l'indentation est inconsistente maintenant

2017-04-02 18:41 UTC, lmazuel commented on src/main/java/fr/onagui/control/AlignmentControler.java
> +		if(  date1 != null ) {
Idealement, si la date est optionnelle, utiliser de "Optional" de Java8

2017-04-02 18:41 UTC, lmazuel commented on src/main/java/fr/onagui/alignment/OntoContainer.java
> +	public Date getModifiedDate(ONTORES cpt);
Idealement un "Optional" de Java8 (voir remarques plus loin)

2017-04-02 18:41 UTC, lmazuel commented on src/main/java/fr/onagui/control/AlignmentControler.java
> +				if(datelue1==null){
Cette lambda serait grandement meilleure si getModified renvoyait un Optional

2017-04-02 18:41 UTC, lmazuel commented on src/main/java/fr/onagui/gui/LabelMethodParameterDialog.java
> +	public Date getDate1AsDate() throws ParseException {
Incoherent:
- throws ParseException
- commentaire dit "null si le parsing echoue"

D'instinct je laisserai allre l'exception si le parsing echoue car c'est une erreur de saisie utilisateur et probablement qu'on veut le gérer plus haut avec un message d'erreur Swing

2017-04-02 18:41 UTC, lmazuel commented on src/main/java/fr/onagui/gui/LabelMethodParameterDialog.java
> +	public Date getDate1AsDate() throws ParseException {
Je vois plus loin que c'est le "throws ParseException" qui est incorrect dans l'implementation actuelle. Je persiste à penser que l'exception c'est mieux, à moins qu'il est un code ailleurs pour dire "if null => Dialog("Erreur de Saisie")

2017-04-02 18:41 UTC, lmazuel commented on src/test/java/MyOntoContainerTestAdapter.java
> +	public Date getModifiedDate(ONTORES cpt) {
Raison de plus pour faire un test :)
Ici c'est des mock, donc les tests c'est 5 minutes de code

2017-04-03 16:12 UTC, lmazuel requested changes

2017-04-03 16:12 UTC, lmazuel commented on src/main/java/fr/onagui/alignment/container/OWLAPIContainer.java
> +	private Repository triplestore = null;
Je ne vois pas pourquoi?

2017-04-03 16:12 UTC, lmazuel commented on src/main/java/fr/onagui/alignment/container/OWLAPIContainer.java
> +		return null;
throw new UnsupportedOperationException("Not supported in OWL for now");

2017-04-03 16:12 UTC, lmazuel commented on src/main/java/fr/onagui/alignment/container/SKOSContainer.java
> +	private Optional<Date>date;
date ne peut pas etre une variable globale

2017-04-03 16:12 UTC, lmazuel commented on src/main/java/fr/onagui/control/AlignmentControler.java
> +		if(  date1.isPresent()) {
C'est beau :)

2017-04-03 16:12 UTC, lmazuel commented on src/main/java/fr/onagui/gui/LabelMethodParameterDialog.java
> +	public Optional<Date> getDate2AsDate() throws Exception {
Toujours le meme probleme, en lisant le code on voit bien que cette fonction ne peut pas renvoyer d'exception. Meme si elle peut, "throws Exception" n'est pas conforme avec la javadoc

2017-04-12 01:11 UTC, lmazuel commented on src/main/java/fr/onagui/alignment/container/OWLAPIContainer.java
> +		return null;
@tfrancart @LYNCETECH A prendre en compte svp

2017-04-12 07:37 UTC, tfrancart commented on src/main/java/fr/onagui/alignment/container/OWLAPIContainer.java
> +		return null;
@lmazuel il me semble bien avoir pris en compte ta demande sur la bonne branche : https://github.com/tfrancart/onagui/blob/issue15/src/main/java/fr/onagui/alignment/container/OWLAPIContainer.java#L330

2017-04-12 07:37 UTC, tfrancart commented on src/main/java/fr/onagui/alignment/container/OWLAPIContainer.java
> +		return null;
ou alors il y a un truc avec Github que je pige pas ?

2017-04-18 01:44 UTC, lmazuel requested changes
Un commentaire bloquant sur un "null" au lieu de "empty()" et je merge @tfrancart @LYNCETECH

2017-04-18 01:44 UTC, lmazuel commented on src/main/java/fr/onagui/alignment/container/SKOSContainer.java
> +		Optional<Date>date=null;
Use "empty()" instead of null
https://www.quora.com/What-is-the-difference-between-null-and-optional-empty-in-Java8

2017-04-18 01:44 UTC, lmazuel commented on src/test/java/MyOntoContainerTestAdapter.java
> +		return null;
Meme le test devrait renvoyer une NotImplementedException, mais c'est no bloquant ici (juste un conseil)

2017-04-18 07:38 UTC, tfrancart commented on src/test/java/MyOntoContainerTestAdapter.java
> +		return null;
Ca se discute; cette classe est un espèce de "mock object", qui est faite pour être sous-classée; si on suit ce raisonnement toutes ses méthodes devrait renvoyer l'exception. Mais bon, j'ai ajouté l'exception dans cette méthode.

2017-04-18 14:52 UTC, lmazuel approved these changes

2017-04-18 14:52 UTC, merged