Issue12
lmazuel/onagui pull request #30
Opened 2017-03-31 10:52 UTC by tfrancart

Ajout d'un menu pour switcher la langue et ajout d'une classe permettant de lancer l'application en ayant directement loader les 2 vocabulaires + l'alignement

2017-04-02 18:26 UTC, lmazuel requested changes
Convention de nommage + fonctionnement de la variable d'environement.

2017-04-02 18:26 UTC, lmazuel commented on src/main/java/fr/onagui/gui/Messages.java
> +			Locale.setDefault(new Locale("en"));
Tout le concept de ce "if", c'est de changer la langue en fonction de la variable d'environement. Donc changer cette ligne casse ce fonctionnement.

2017-04-02 18:26 UTC, lmazuel commented on src/main/java/fr/onagui/gui/Messages.java
> +		System.out.println(langue);
Soit retirer le print, soit metre un message un peu plus clair 
"Changing language: "+langue

2017-04-02 18:26 UTC, lmazuel commented on src/main/resources/messages.properties
> +Anglais=English
Clef devrait etre "English", pas "Anglais". Les clefs du fichier de configuration devraient etre en anglais.

2017-04-02 18:26 UTC, lmazuel commented on src/main/resources/messages.properties
> +Francais=Fran�ais
Clef devrait etre "French", pas "Francais". Les clefs du fichier de configuration devraient etre en anglais.

2017-04-02 18:26 UTC, lmazuel commented on src/main/resources/messages_fr.properties
> +Anglais=English
Clef devrait etre "English", pas "Anglais". Les clefs du fichier de configuration devraient etre en anglais.

2017-04-02 18:26 UTC, lmazuel commented on src/main/resources/messages_fr.properties
> +Francais=Fran�ais
Clef devrait etre "French", pas "Francais". Les clefs du fichier de configuration devraient etre en anglais.

2017-04-03 14:10 UTC, tfrancart commented
OK vu. Désolé c'était un reliquat des tests.
Il y a un conflit lors du merge mais je ne sais pas bien quelle serait la procédure pour le régler.

2017-04-03 15:21 UTC, lmazuel approved these changes

2017-04-03 15:23 UTC, lmazuel commented
@tfrancart @LYNCETECH Le conflit est parceque vous avez exrait le chargement de l'ontologie dans une méthode "loadOntologyFromFileReference" (ce qui est bien :)). Une des branches contient l'ancienne version, l'autre la nouvelle

2017-04-12 01:08 UTC, merged